'use strict';

// Explicit migration registry for tests that have proved they do not need the
// application DOM, index.html, or integration vendor stubs.  Keep this list
// reviewable: a test enters the Node layer only after it passes there.
const NODE_UNIT_TESTS = Object.freeze([
  '__tests__/box.advisor.test.js',
  '__tests__/box.assumptions.test.js',
  '__tests__/box.axisAutoScale.test.js',
  '__tests__/box.barNegativeGeometry.test.js',
  '__tests__/box.fillColorTheme.test.js',
  '__tests__/box.pointConnections.test.js',
  '__tests__/box.summary.performance.test.js',
  '__tests__/box.summaryOverlayColor.test.js',
  '__tests__/unit/box.swarm.model.test.js',
  '__tests__/colorSchemes.colorMath.test.js',
  '__tests__/component.load-benchmark.test.js',
  '__tests__/unit/componentLifecycle.model.test.js',
  '__tests__/dataPipeline.test.js',
  '__tests__/dataTransforms.test.js',
  '__tests__/desktopCommands.test.js',
  '__tests__/exampleDatasets.biomedical.test.js',
  '__tests__/formulaEngine.test.js',
  '__tests__/forecast.regression.test.js',
  '__tests__/box.statsTestSelection.model.test.js',
  '__tests__/regression.reportingNotation.test.js',
  '__tests__/renderCacheSchema.test.js',
  '__tests__/resampling.contract.test.js',
  '__tests__/regression.catalog.test.js',
  '__tests__/scatter.sharedStatisticsPrimitives.test.js',
  '__tests__/stats.adjust.test.js',
  '__tests__/stats.goodnessOfFit.test.js',
  '__tests__/stats.pvalue.corrections.test.js',
  '__tests__/svgGeometry.test.js',
  '__tests__/theme.adapters.test.js',
  '__tests__/theme.catalog.test.js',
  '__tests__/theme.compiler.test.js',
  '__tests__/cartesianLayout.test.js',
  '__tests__/dataViewPersistence.test.js',
  '__tests__/stringAnalysis.test.js',
  '__tests__/uniprot.test.js',
  '__tests__/graphArchive.adaptiveCompression.test.js',
  '__tests__/graphArchive.payloadLiteLoad.test.js',
  '__tests__/graphArchive.roundtrip.components.test.js',
  '__tests__/debug.contract.test.js',
  '__tests__/simple-performance.test.js',
  '__tests__/performance.test.js',
  '__tests__/box.stats.fallback.test.js',
  '__tests__/chartStyle.axisTicks.buildScale.test.js',
  '__tests__/chartStyle.axisTicks.logScale.test.js',
  '__tests__/chartStyle.xAxisEndpointMargins.test.js',
  '__tests__/chartStyle.formatScientific.test.js',
  '__tests__/renderCacheDiagnostics.contract.test.js',
  '__tests__/snapshotPolicy.recoveryParity.test.js',
  '__tests__/stats.audit.remediation.core.test.js',
  '__tests__/stats.figureSummary.reportingMatrix.test.js',
  '__tests__/stats.audit.remediation.components.test.js',
  '__tests__/goAnalysis.test.js',
  '__tests__/box.statsModelOwnership.contract.test.js',
  '__tests__/hot.uiState.test.js',
  '__tests__/scatter.pointContextMenuSelection.test.js',
  '__tests__/roc.classificationSetup.test.js',
  '__tests__/line.regressionOverlaySegmentation.test.js',
  '__tests__/unit/line.model.test.js',
  '__tests__/unit/regression.logisticSummary.test.js',
  '__tests__/scatter.pointStyleOverrides.test.js',
  '__tests__/scatter.regressionOverlayRange.test.js',
  '__tests__/welcome.example-assets.test.js'
]);

const NODE_UNIT_TEST_SET = new Set(NODE_UNIT_TESTS);

const DOM_UNIT_TESTS = Object.freeze([
  '__tests__/box.liveStyleRefresh.test.js',
  '__tests__/box.significanceWhiskers.test.js',
  '__tests__/box.statsReportingSurface.contract.test.js',
  '__tests__/box.swarmOffsets.test.js',
  '__tests__/colorPicker.toolbarOwnership.test.js',
  '__tests__/colorSchemes.core.test.js',
  '__tests__/colorSchemes.customChoice.test.js',
  '__tests__/colorSchemes.defaultIsolation.test.js',
  '__tests__/colorSchemes.undo.test.js',
  '__tests__/symbolToolbar.numericFormatting.test.js',
  '__tests__/stats.abbreviations.test.js',
  '__tests__/stats.inference.contract.test.js',
  '__tests__/stats.pvalueFormatting.contract.test.js',
  '__tests__/stats-table.figureSummary.semantic.test.js',
  '__tests__/dom.autoResizeSvg.test.js',
  '__tests__/dom.enableLabelDrag.test.js',
  '__tests__/dom.enableLegendDrag.test.js',
  '__tests__/dom.framePublication.test.js',
  '__tests__/dom.titleEmptyEdit.test.js',
  '__tests__/exportProjection.contract.test.js',
  '__tests__/visualProjection.test.js',
  '__tests__/main.components.ensureComponent.test.js',
  '__tests__/domControls.defaultPayloadIsolation.test.js',
  '__tests__/domControls.payloadSizingOwnership.test.js',
  '__tests__/fontControls.colorParsing.test.js',
  '__tests__/fontControls.debugLogging.test.js',
  '__tests__/fontControls.legendBorder.test.js',
  '__tests__/fontControls.openerClickGuard.test.js',
  '__tests__/fontControls.proportionalFontResize.test.js',
  '__tests__/fontControls.tabIsolation.test.js',
  '__tests__/fontControls.titleVisibility.test.js',
  '__tests__/hot.aggrid.dimensions.test.js',
  '__tests__/hot.aggrid.binding.selection-and-payload.test.js',
  '__tests__/hot.aggrid.binding.editor-behavior.test.js',
  '__tests__/hot.aggrid.binding.filters-and-analysis.test.js',
  '__tests__/hot.aggrid.binding.structural-and-scroll.test.js',
  '__tests__/hot.aggrid.clipboard-selection.paste-and-selection.test.js',
  '__tests__/hot.aggrid.clipboard-selection.selection-geometry.test.js',
  '__tests__/hot.aggrid.clipboard-selection.column-reorder.test.js',
  '__tests__/hot.aggrid.clipboard-selection.menus-and-filtering.test.js',
  '__tests__/hot.aggrid.clipboard-selection.clipboard.test.js',
  '__tests__/hot.aggrid.clipboard-selection.clipboard-undo.test.js',
  '__tests__/hot.exclusionPersistence.test.js',
  '__tests__/styleUndo.test.js',
  '__tests__/workspaceTabs.schedulerIsolation.test.js',
  '__tests__/workspaceToolbar.numericWheel.test.js',
  '__tests__/workspaceToolbar.overflow.test.js',
  '__tests__/dendrogramControls.numericWheel.test.js',
  '__tests__/dom/formControls.autosize.test.js',
  '__tests__/dom/heatmap.model.test.js',
  '__tests__/welcome.ready.test.js',
  '__tests__/heatmap.dendrogram-rendering.test.js',
  '__tests__/roc.statistics.standard.test.js',
  '__tests__/venn.labelLayout.test.js',
  '__tests__/dataViews.exportTabs.test.js',
  '__tests__/gridControls.liveProjection.test.js',
  '__tests__/significanceControls.overlay.test.js',
  '__tests__/notes.mountFoldable.test.js',
  '__tests__/toolbarOverflow.test.js',
  '__tests__/symbolToolbar.undo.test.js',
  '__tests__/chartStyle.defaultGraphSize.test.js',
  '__tests__/chartStyle.fontLabel.test.js',
  '__tests__/chartStyle.svgPreparation.test.js',
  '__tests__/chartStyle.fontResize.tabscope.test.js',
  '__tests__/chartStyle.axisResizeMargins.test.js',
  '__tests__/chartStyle.labelOrientation.test.js',
  '__tests__/chartStyle.xAxisLabelAngle.test.js',
  '__tests__/chartStyle.bottomLayout.test.js',
  '__tests__/chartStyle.statsAnnotation.test.js',
  '__tests__/chartStyle.fontResize.test.js',
  '__tests__/chartStyle.legendViewport.test.js',
  '__tests__/chartStyle.pointLabelLayout.test.js',
  '__tests__/publicationStyles.core.test.js',
  '__tests__/previews.pngFallback.test.js',
  '__tests__/requested-defaults.contract.test.js',
  '__tests__/scatter.adaptiveSize.test.js',
  '__tests__/exporter.dropdownStacking.test.js',
  '__tests__/exporter.statsFigureSummary.test.js',
  '__tests__/exporter.significanceHitOverlay.test.js',
  '__tests__/exporter.hybridSource.test.js',
  '__tests__/exporter.physicalProjection.test.js',
  '__tests__/exporter.inkscapeUngroupStability.test.js',
  '__tests__/exporter.savePicker.test.js',
  '__tests__/exporter.scatterOptimization.test.js',
  '__tests__/fileIO.activation.test.js',
  '__tests__/graphArchive.renderCacheSerialization.test.js',
  '__tests__/tabSwitch.reuseCache.test.js',
  '__tests__/documentState.recoveryThrottle.test.js',
  '__tests__/sessionActions.saveLazyBuild.test.js',
  '__tests__/sessionActions.restoreParity.test.js',
  '__tests__/session.assignTabPayload.assignment-guards.test.js',
  '__tests__/session.assignTabPayload.cache-capture.test.js',
  '__tests__/session.assignTabPayload.dirty-state.test.js',
  '__tests__/session.assignTabPayload.canonical-ui-events.test.js',
  '__tests__/session.assignTabPayload.signature-and-cache-persistence.test.js',
  '__tests__/tableImport.formats.test.js',
  '__tests__/dom/tableImport.affordances.test.js',
  '__tests__/tableImport.paste.aggrid.test.js',
  '__tests__/tableImport.prism.test.js',
  '__tests__/tabs.documentOperation.test.js',
  '__tests__/additionalLineControls.pathCompatibility.test.js',
  '__tests__/axisControls.init.test.js',
  '__tests__/resizer.canvasReuse.test.js',
  '__tests__/resizer.optionsMenu.test.js',
  '__tests__/resizer.panelLayoutPersistence.test.js',
  '__tests__/componentLayout.zoomBehavior.test.js',
  '__tests__/componentLifecycle.core.authority-and-readiness.test.js',
  '__tests__/componentLifecycle.core.cache-and-editing.test.js',
  '__tests__/componentLifecycle.core.payload-and-async.test.js',
  '__tests__/componentLifecycle.core.runtime-ownership.test.js',
  '__tests__/componentLifecycle.core.restore-and-scheduling.test.js',
  '__tests__/componentLifecycle.core.cleanup-and-publication.test.js',
  '__tests__/jobs.controller.test.js',
  '__tests__/graphSizing.defaultBaseline.test.js',
  '__tests__/hist.drawableFrame.test.js',
  '__tests__/hist.panel-layout.test.js',
  '__tests__/stats.reporting.layout.test.js',
  '__tests__/stats.reportingNotation.test.js',
  '__tests__/stats.figureSummary.state.contract.test.js',
  '__tests__/stats.figureSummary.renderer.contract.test.js',
  '__tests__/componentLifecycle.ownerPersistence.test.js',
  '__tests__/componentDrawableFrame.authority.test.js',
  '__tests__/stats.inference.tabIsolation.test.js',
  '__tests__/stats.pvalueFormat.tabIsolation.test.js',
  '__tests__/theme.runtime.test.js',
  '__tests__/pca.pointStyleScopes.test.js',
  '__tests__/surface.legendResize.test.js',
  '__tests__/toolbar.numericWheel.sharedControls.test.js',
  '__tests__/tableImport.ownerTransaction.test.js',
  '__tests__/shared/plot3d.test.js',
  '__tests__/hist.schedulerOwnership.test.js'
]);

const DOM_UNIT_TEST_SET = new Set(DOM_UNIT_TESTS);

const ARCHITECTURE_TESTS = Object.freeze([
  '__tests__/audit.remaining-issues.contract.test.js',
  '__tests__/axis-major-tick-length.contract.test.js',
  '__tests__/axis-toolbar-layout.contract.test.js',
  '__tests__/architecture/graph.exportControlsAlignment.contract.test.js',
  '__tests__/box.architectureOwnership.contract.test.js',
  '__tests__/box.frameCommit.contract.test.js',
  '__tests__/box.internalSanitation.contract.test.js',
  '__tests__/box.referenceStats.contract.test.js',
  '__tests__/box.statsAspect.contract.test.js',
  '__tests__/box.statsStatePerformance.contract.test.js',
  '__tests__/box.stripDatasetGap.regression.test.js',
  '__tests__/box.stripRadius.regression.test.js',
  '__tests__/component.exportProjectionWiring.test.js',
  '__tests__/component.exportSources.test.js',
  '__tests__/componentImportBindings.test.js',
  '__tests__/dataViews.payloadRaw.contract.test.js',
  '__tests__/generateComponentContracts.check.test.js',
  '__tests__/graph.horizontalGutter.contract.test.js',
  '__tests__/graphArchive.worker.schema.test.js',
  '__tests__/graphFileOwnership.contract.test.js',
  '__tests__/architecture/hot.pasteScheduling.contract.test.js',
  '__tests__/hist.stats-font.contract.test.js',
  '__tests__/letterSpacing.contract.test.js',
  '__tests__/unit/ownerPayloadDriver.contract.test.js',
  '__tests__/pca.lifecycleOwnership.contract.test.js',
  '__tests__/roc.statsPanelOwnership.contract.test.js',
  '__tests__/runtime.localDependencies.test.js',
  '__tests__/scatter.internalArchitecture.contract.test.js',
  '__tests__/scatter.listenerBinding.contract.test.js',
  '__tests__/statistics.cross-component.regression.test.js',
  '__tests__/stats.inference.components.contract.test.js',
  '__tests__/stats.ownerNormalization.contract.test.js',
  '__tests__/ownerCapture.normalization.contract.test.js',
  '__tests__/svgComposition.contract.test.js',
  '__tests__/welcome.icons.contract.test.js',
  '__tests__/workers.localDependencies.test.js'
]);

const ARCHITECTURE_TEST_SET = new Set(ARCHITECTURE_TESTS);

const STATISTICAL_ORACLE_TESTS = Object.freeze([
  '__tests__/stats.differential.python.test.js',
  '__tests__/stats.component.differential.test.js',
  '__tests__/stats.matrix.components.test.js',
  '__tests__/stats.extended.coverage.test.js',
  '__tests__/stats.ui.presentation.branches.test.js',
  '__tests__/stats.ui.persistence.restore.test.js'
]);

const STATISTICAL_ORACLE_TEST_SET = new Set(STATISTICAL_ORACLE_TESTS);

function normalizePath(file) {
  return String(file || '').replace(/\\/g, '/').replace(/^\.\//, '');
}

function getExplicitLayer(file) {
  const normalized = normalizePath(file);
  if (NODE_UNIT_TEST_SET.has(normalized)) return 'unit-node';
  if (DOM_UNIT_TEST_SET.has(normalized)) return 'dom-unit';
  if (ARCHITECTURE_TEST_SET.has(normalized)) return 'architecture';
  if (STATISTICAL_ORACLE_TEST_SET.has(normalized)) return 'statistical-oracle';
  return null;
}

module.exports = {
  NODE_UNIT_TESTS,
  DOM_UNIT_TESTS,
  ARCHITECTURE_TESTS,
  STATISTICAL_ORACLE_TESTS,
  getExplicitLayer
};
