'use strict';

// Explicit migration registry for tests that have proved they do not need the
// application DOM, index.html, or integration vendor stubs.  Keep this list
// reviewable: a test enters the Node layer only after it passes there.
const NODE_UNIT_TESTS = Object.freeze([
  '__tests__/unit/box.advisor.test.js',
  '__tests__/unit/box.assumptions.test.js',
  '__tests__/unit/box.axisAutoScale.test.js',
  '__tests__/unit/box.barNegativeGeometry.test.js',
  '__tests__/unit/box.fillColorTheme.test.js',
  '__tests__/unit/box.pointConnections.test.js',
  '__tests__/unit/box.summary.performance.test.js',
  '__tests__/unit/box.summaryOverlayColor.test.js',
  '__tests__/unit/box.swarm.model.test.js',
  '__tests__/unit/colorSchemes.colorMath.test.js',
  '__tests__/unit/component.load-benchmark.test.js',
  '__tests__/unit/componentLifecycle.model.test.js',
  '__tests__/unit/dataPipeline.test.js',
  '__tests__/unit/dataTransforms.test.js',
  '__tests__/unit/desktopCommands.test.js',
  '__tests__/unit/exampleDatasets.biomedical.test.js',
  '__tests__/unit/formulaEngine.test.js',
  '__tests__/unit/forecast.regression.test.js',
  '__tests__/unit/box.statsTestSelection.model.test.js',
  '__tests__/unit/regression.reportingNotation.test.js',
  '__tests__/unit/renderCacheSchema.test.js',
  '__tests__/unit/resampling.contract.test.js',
  '__tests__/unit/regression.catalog.test.js',
  '__tests__/unit/scatter.sharedStatisticsPrimitives.test.js',
  '__tests__/unit/stats.adjust.test.js',
  '__tests__/unit/stats.goodnessOfFit.test.js',
  '__tests__/unit/stats.pvalue.corrections.test.js',
  '__tests__/unit/svgGeometry.test.js',
  '__tests__/unit/theme.adapters.test.js',
  '__tests__/unit/theme.catalog.test.js',
  '__tests__/unit/theme.compiler.test.js',
  '__tests__/unit/cartesianLayout.test.js',
  '__tests__/unit/dataViewPersistence.test.js',
  '__tests__/unit/stringAnalysis.test.js',
  '__tests__/unit/uniprot.test.js',
  '__tests__/unit/graphArchive.adaptiveCompression.test.js',
  '__tests__/unit/graphArchive.payloadLiteLoad.test.js',
  '__tests__/unit/graphArchive.roundtrip.components.test.js',
  '__tests__/unit/debug.contract.test.js',
  '__tests__/unit/simple-performance.test.js',
  '__tests__/unit/performance.test.js',
  '__tests__/unit/box.stats.fallback.test.js',
  '__tests__/unit/chartStyle.axisTicks.buildScale.test.js',
  '__tests__/unit/chartStyle.axisTicks.logScale.test.js',
  '__tests__/unit/chartStyle.xAxisEndpointMargins.test.js',
  '__tests__/unit/chartStyle.formatScientific.test.js',
  '__tests__/unit/chartStyle.formatAxisValue.test.js',
  '__tests__/unit/renderCacheDiagnostics.contract.test.js',
  '__tests__/unit/snapshotPolicy.recoveryParity.test.js',
  '__tests__/unit/stats.audit.remediation.core.test.js',
  '__tests__/unit/stats.figureSummary.reportingMatrix.test.js',
  '__tests__/unit/stats.audit.remediation.components.test.js',
  '__tests__/unit/goAnalysis.test.js',
  '__tests__/unit/box.statsModelOwnership.contract.test.js',
  '__tests__/unit/hot.uiState.test.js',
  '__tests__/unit/scatter.pointContextMenuSelection.test.js',
  '__tests__/unit/roc.classificationSetup.test.js',
  '__tests__/unit/line.regressionOverlaySegmentation.test.js',
  '__tests__/unit/line.model.test.js',
  '__tests__/unit/regression.logisticSummary.test.js',
  '__tests__/unit/scatter.pointStyleOverrides.test.js',
  '__tests__/unit/scatter.regressionOverlayRange.test.js',
  '__tests__/unit/welcome.example-assets.test.js'
]);

const NODE_UNIT_TEST_SET = new Set(NODE_UNIT_TESTS);

const DOM_UNIT_TESTS = Object.freeze([
  '__tests__/dom/box.liveStyleRefresh.test.js',
  '__tests__/dom/box.significanceWhiskers.test.js',
  '__tests__/dom/box.statsReportingSurface.contract.test.js',
  '__tests__/dom/box.renderImpact.contract.test.js',
  '__tests__/dom/box.swarmOffsets.test.js',
  '__tests__/dom/colorPicker.toolbarOwnership.test.js',
  '__tests__/dom/colorSchemes.core.test.js',
  '__tests__/dom/colorSchemes.customChoice.test.js',
  '__tests__/dom/colorSchemes.defaultIsolation.test.js',
  '__tests__/dom/colorSchemes.undo.test.js',
  '__tests__/dom/symbolToolbar.numericFormatting.test.js',
  '__tests__/dom/stats.abbreviations.test.js',
  '__tests__/dom/stats.inference.contract.test.js',
  '__tests__/dom/stats.pvalueFormatting.contract.test.js',
  '__tests__/dom/stats-table.figureSummary.semantic.test.js',
  '__tests__/dom/dom.autoResizeSvg.test.js',
  '__tests__/dom/dom.enableLabelDrag.test.js',
  '__tests__/dom/dom.enableLegendDrag.test.js',
  '__tests__/dom/dom.framePublication.test.js',
  '__tests__/dom/dom.titleEmptyEdit.test.js',
  '__tests__/dom/exportProjection.contract.test.js',
  '__tests__/dom/visualProjection.test.js',
  '__tests__/dom/main.components.ensureComponent.test.js',
  '__tests__/dom/domControls.defaultPayloadIsolation.test.js',
  '__tests__/dom/domControls.payloadSizingOwnership.test.js',
  '__tests__/dom/fontControls.colorParsing.test.js',
  '__tests__/dom/fontControls.debugLogging.test.js',
  '__tests__/dom/fontControls.legendBorder.test.js',
  '__tests__/dom/fontControls.openerClickGuard.test.js',
  '__tests__/dom/fontControls.proportionalFontResize.test.js',
  '__tests__/dom/fontControls.tabIsolation.test.js',
  '__tests__/dom/fontControls.titleVisibility.test.js',
  '__tests__/dom/hot.aggrid.dimensions.test.js',
  '__tests__/dom/hot.aggrid.binding.selection-and-payload.test.js',
  '__tests__/dom/hot.aggrid.binding.editor-behavior.test.js',
  '__tests__/dom/hot.aggrid.binding.filters-and-analysis.test.js',
  '__tests__/dom/hot.aggrid.binding.structural-and-scroll.test.js',
  '__tests__/dom/hot.aggrid.clipboard-selection.paste-and-selection.test.js',
  '__tests__/dom/hot.aggrid.clipboard-selection.selection-geometry.test.js',
  '__tests__/dom/hot.aggrid.clipboard-selection.column-reorder.test.js',
  '__tests__/dom/hot.aggrid.clipboard-selection.menus-and-filtering.test.js',
  '__tests__/dom/hot.aggrid.clipboard-selection.clipboard.test.js',
  '__tests__/dom/hot.aggrid.clipboard-selection.clipboard-undo.test.js',
  '__tests__/dom/hot.exclusionPersistence.test.js',
  '__tests__/dom/styleUndo.test.js',
  '__tests__/dom/workspaceTabs.schedulerIsolation.test.js',
  '__tests__/dom/workspaceToolbar.numericWheel.test.js',
  '__tests__/dom/workspaceToolbar.overflow.test.js',
  '__tests__/dom/dendrogramControls.numericWheel.test.js',
  '__tests__/dom/formControls.autosize.test.js',
  '__tests__/dom/heatmap.model.test.js',
  '__tests__/dom/welcome.ready.test.js',
  '__tests__/dom/heatmap.dendrogram-rendering.test.js',
  '__tests__/dom/roc.statistics.standard.test.js',
  '__tests__/dom/venn.labelLayout.test.js',
  '__tests__/dom/dataViews.exportTabs.test.js',
  '__tests__/dom/gridControls.liveProjection.test.js',
  '__tests__/dom/significanceControls.overlay.test.js',
  '__tests__/dom/notes.mountFoldable.test.js',
  '__tests__/dom/toolbarOverflow.test.js',
  '__tests__/dom/symbolToolbar.undo.test.js',
  '__tests__/dom/chartStyle.defaultGraphSize.test.js',
  '__tests__/dom/chartStyle.fontLabel.test.js',
  '__tests__/dom/chartStyle.svgPreparation.test.js',
  '__tests__/dom/chartStyle.fontResize.tabscope.test.js',
  '__tests__/dom/chartStyle.axisResizeMargins.test.js',
  '__tests__/dom/chartStyle.labelOrientation.test.js',
  '__tests__/dom/chartStyle.xAxisLabelAngle.test.js',
  '__tests__/dom/chartStyle.bottomLayout.test.js',
  '__tests__/dom/chartStyle.statsAnnotation.test.js',
  '__tests__/dom/chartStyle.fontResize.test.js',
  '__tests__/dom/chartStyle.legendViewport.test.js',
  '__tests__/dom/chartStyle.pointLabelLayout.test.js',
  '__tests__/dom/publicationStyles.core.test.js',
  '__tests__/dom/previews.pngFallback.test.js',
  '__tests__/dom/renderImpact.components.contract.test.js',
  '__tests__/dom/requested-defaults.contract.test.js',
  '__tests__/dom/scatter.adaptiveSize.test.js',
  '__tests__/dom/exporter.dropdownStacking.test.js',
  '__tests__/dom/exporter.statsFigureSummary.test.js',
  '__tests__/dom/exporter.significanceHitOverlay.test.js',
  '__tests__/dom/exporter.hybridSource.test.js',
  '__tests__/dom/exporter.physicalProjection.test.js',
  '__tests__/dom/exporter.inkscapeUngroupStability.test.js',
  '__tests__/dom/exporter.savePicker.test.js',
  '__tests__/dom/exporter.scatterOptimization.test.js',
  '__tests__/dom/exporter.firefoxSvgCopy.test.js',
  '__tests__/dom/fileIO.activation.test.js',
  '__tests__/dom/graphArchive.renderCacheSerialization.test.js',
  '__tests__/dom/tabSwitch.reuseCache.test.js',
  '__tests__/dom/documentState.recoveryThrottle.test.js',
  '__tests__/integration/sessionActions.saveLazyBuild.test.js',
  '__tests__/dom/sessionActions.restoreParity.test.js',
  '__tests__/dom/session.assignTabPayload.assignment-guards.test.js',
  '__tests__/dom/session.assignTabPayload.cache-capture.test.js',
  '__tests__/dom/session.assignTabPayload.dirty-state.test.js',
  '__tests__/dom/session.assignTabPayload.canonical-ui-events.test.js',
  '__tests__/dom/session.assignTabPayload.signature-and-cache-persistence.test.js',
  '__tests__/dom/tableImport.formats.test.js',
  '__tests__/dom/tableImport.firefoxExcelPaste.test.js',
  '__tests__/dom/tableImport.affordances.test.js',
  '__tests__/dom/tableImport.paste.aggrid.test.js',
  '__tests__/dom/tableImport.prism.test.js',
  '__tests__/dom/tabs.documentOperation.test.js',
  '__tests__/dom/additionalLineControls.pathCompatibility.test.js',
  '__tests__/dom/axisControls.init.test.js',
  '__tests__/dom/resizer.canvasReuse.test.js',
  '__tests__/dom/resizer.optionsMenu.test.js',
  '__tests__/dom/resizer.panelLayoutPersistence.test.js',
  '__tests__/dom/componentLayout.zoomBehavior.test.js',
  '__tests__/dom/componentLifecycle.core.authority-and-readiness.test.js',
  '__tests__/dom/componentLifecycle.core.cache-and-editing.test.js',
  '__tests__/dom/componentLifecycle.core.payload-and-async.test.js',
  '__tests__/dom/componentLifecycle.core.runtime-ownership.test.js',
  '__tests__/dom/componentLifecycle.core.restore-and-scheduling.test.js',
  '__tests__/dom/componentLifecycle.core.cleanup-and-publication.test.js',
  '__tests__/dom/jobs.controller.test.js',
  '__tests__/dom/graphSizing.defaultBaseline.test.js',
  '__tests__/dom/hist.drawableFrame.test.js',
  '__tests__/dom/hist.panel-layout.test.js',
  '__tests__/dom/stats.reporting.layout.test.js',
  '__tests__/dom/stats.reportingNotation.test.js',
  '__tests__/dom/stats.figureSummary.state.contract.test.js',
  '__tests__/dom/stats.figureSummary.renderer.contract.test.js',
  '__tests__/dom/componentLifecycle.ownerPersistence.test.js',
  '__tests__/dom/componentDrawableFrame.authority.test.js',
  '__tests__/dom/stats.inference.tabIsolation.test.js',
  '__tests__/dom/stats.pvalueFormat.tabIsolation.test.js',
  '__tests__/dom/theme.runtime.test.js',
  '__tests__/dom/pca.pointStyleScopes.test.js',
  '__tests__/dom/surface.legendResize.test.js',
  '__tests__/dom/toolbar.numericWheel.sharedControls.test.js',
  '__tests__/dom/tableImport.ownerTransaction.test.js',
  '__tests__/shared/plot3d.test.js',
  '__tests__/dom/hist.schedulerOwnership.test.js'
]);

const DOM_UNIT_TEST_SET = new Set(DOM_UNIT_TESTS);

const ARCHITECTURE_TESTS = Object.freeze([
  '__tests__/architecture/audit.remaining-issues.contract.test.js',
  '__tests__/architecture/axis-major-tick-length.contract.test.js',
  '__tests__/architecture/axis-toolbar-layout.contract.test.js',
  '__tests__/architecture/graph.exportControlsAlignment.contract.test.js',
  '__tests__/architecture/box.architectureOwnership.contract.test.js',
  '__tests__/architecture/box.frameCommit.contract.test.js',
  '__tests__/architecture/box.internalSanitation.contract.test.js',
  '__tests__/architecture/box.referenceStats.contract.test.js',
  '__tests__/architecture/box.statsAspect.contract.test.js',
  '__tests__/architecture/box.statsStatePerformance.contract.test.js',
  '__tests__/architecture/box.stripDatasetGap.regression.test.js',
  '__tests__/architecture/box.stripRadius.regression.test.js',
  '__tests__/architecture/component.exportProjectionWiring.test.js',
  '__tests__/architecture/componentImportBindings.test.js',
  '__tests__/architecture/dataViews.payloadRaw.contract.test.js',
  '__tests__/architecture/generateComponentContracts.check.test.js',
  '__tests__/architecture/graph.horizontalGutter.contract.test.js',
  '__tests__/architecture/graphArchive.worker.schema.test.js',
  '__tests__/architecture/graphFileOwnership.contract.test.js',
  '__tests__/architecture/hot.pasteScheduling.contract.test.js',
  '__tests__/architecture/hist.stats-font.contract.test.js',
  '__tests__/architecture/letterSpacing.contract.test.js',
  '__tests__/architecture/pca.lifecycleOwnership.contract.test.js',
  '__tests__/architecture/productionBootstrap.manifest.contract.test.js',
  '__tests__/architecture/roc.statsPanelOwnership.contract.test.js',
  '__tests__/architecture/runtime.localDependencies.test.js',
  '__tests__/architecture/scatter.internalArchitecture.contract.test.js',
  '__tests__/architecture/scatter.listenerBinding.contract.test.js',
  '__tests__/architecture/statistics.cross-component.regression.test.js',
  '__tests__/architecture/stats.inference.components.contract.test.js',
  '__tests__/architecture/stats.ownerNormalization.contract.test.js',
  '__tests__/architecture/ownerCapture.normalization.contract.test.js',
  '__tests__/architecture/svgComposition.contract.test.js',
  '__tests__/architecture/welcome.icons.contract.test.js',
  '__tests__/architecture/workers.localDependencies.test.js'
]);

const ARCHITECTURE_TEST_SET = new Set(ARCHITECTURE_TESTS);

const STATISTICAL_ORACLE_TESTS = Object.freeze([
  '__tests__/statistical-oracle/stats.differential.python.test.js',
  '__tests__/statistical-oracle/stats.component.differential.test.js',
  '__tests__/statistical-oracle/stats.matrix.components.test.js',
  '__tests__/statistical-oracle/stats.extended.coverage.test.js',
  '__tests__/statistical-oracle/stats.ui.presentation.branches.test.js',
  '__tests__/statistical-oracle/stats.ui.persistence.restore.test.js'
]);

const STATISTICAL_ORACLE_TEST_SET = new Set(STATISTICAL_ORACLE_TESTS);

function normalizePath(file) {
  return String(file || '').replace(/\\/g, '/').replace(/^\.\//, '');
}

function getExplicitLayer(file) {
  const normalized = normalizePath(file);
  if (NODE_UNIT_TEST_SET.has(normalized)) return 'unit-node';
  if (DOM_UNIT_TEST_SET.has(normalized)) return 'dom-unit';
  if (ARCHITECTURE_TEST_SET.has(normalized)) return 'architecture';
  if (STATISTICAL_ORACLE_TEST_SET.has(normalized)) return 'statistical-oracle';
  return null;
}

module.exports = {
  NODE_UNIT_TESTS,
  DOM_UNIT_TESTS,
  ARCHITECTURE_TESTS,
  STATISTICAL_ORACLE_TESTS,
  getExplicitLayer
};
